name: nheko debian build

on: workflow_dispatch
  
jobs:
  ubuntu:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2
        with:
          repository: Nheko-Reborn/nheko
          # ref: main

      - name: repo
        run:  echo "deb http://azure.archive.ubuntu.com/ubuntu/ impish main restricted universe multiverse" |sudo tee /etc/apt/sources.list.d/qtnew.list

      - name: update
        run:  sudo apt update


      - name: dependencies
        run: |
          sudo apt install \
                g++ cmake zlib1g-dev libssl-dev \
                qt{base,declarative,tools,multimedia,quickcontrols2-}5-dev \
                libqt5svg5-dev libboost-system-dev libboost-thread-dev \
                libboost-iostreams-dev libolm-dev liblmdb++-dev libcmark-dev \
                nlohmann-json3-dev libspdlog-dev libgtest-dev \
                qml-module-qt{gstreamer,multimedia,quick-extras,-labs-settings,-labs-platform,graphicaleffects,quick-controls2} \
                qt5keychain-dev libevent-dev libcurl4-gnutls-dev

      - name: build
        run:  |
          cmake -S. -Bbuild -DHUNTER_ENABLED=ON -DBUILD_SHARED_LIBS=OFF -DUSE_BUNDLED_OPENSSL=OFF
          cmake --build build --config Release

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          path: build
